### ISSUE TITLE
Class Number has no method to respond to message '-1/1'

### ISSUE THREAD

**Issue by sarna** [moonglum/halunke#13]
This code:
```
('count_down = {
    |'n|
    (stdio puts (n to_s))
    (count_down call [(n-1)])
})

(count_down call [10])
```
fails with a following message:
```
➜  ~ halunke test.hal
10
Traceback (most recent call last):
        26: from /home/me/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
        25: from /home/me/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
        24: from /home/me/.rvm/gems/ruby-2.5.1/bin/halunke:23:in `<main>'
        23: from /home/me/.rvm/gems/ruby-2.5.1/bin/halunke:23:in `load'
        22: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/exe/halunke:22:in `<top (required)>'
        21: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/interpreter.rb:31:in `eval'
        20: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:4:in `eval'
        19: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:4:in `map'
        18: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:4:in `block in eval'
        17: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:77:in `eval'
        16: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/runtime/hfunction.rb:19:in `receive_message'
        15: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:54:in `block in eval'
        14: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:4:in `eval'
        13: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:4:in `map'
        12: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:4:in `block in eval'
        11: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:77:in `eval'
        10: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:88:in `eval'
         9: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:88:in `each_slice'
         8: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:88:in `each'
         7: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:90:in `block in eval'
         6: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:61:in `eval'
         5: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:61:in `map'
         4: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:61:in `block in eval'
         3: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:77:in `eval'
         2: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/runtime/hnative_object.rb:12:in `receive_message'
         1: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/runtime/hclass.rb:81:in `lookup'
/home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/runtime/hclass.rb:84:in `rescue in lookup': Class Number has no method to respond to message '-1/1' (RuntimeError)
```

**Comment by moonglum** [comment]
There is a Syntax Error in your file: The space between a receiver, and the parts of the message are not optional. So instead of `(n-1)` you need to write `(n - 1)`. I'm thinking about how to fix that. Either by a better error message or by allowing that somehow 🤔 Here is the entire code with the fixed expression:

```
('count_down = {
    |'n|
    (stdio puts (n to_s))
    (count_down call [(n - 1)])
})

(count_down call [10])
```

Does that solve your problem?

**Comment by sarna** [comment]
Yep, it works now :)
I think a better error message would be enough.

**Comment by moonglum** [comment]
@sarna I just released https://github.com/moonglum/halunke/releases/tag/v0.8.0 which addresses this 👍 Thank you again for your feedback 🙇
