### ISSUE TITLE
Destructuring function arguments

### ISSUE THREAD

**Issue by sarna** [moonglum/halunke#14]
This code:
```
('foo = {
    |['a]|
    (stdio puts a)
})

(foo call [["bar"]])
```
crashes the interpreter:
```
➜  ~ halunke test.hal
Traceback (most recent call last):
        15: from /home/me/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
        14: from /home/me/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
        13: from /home/me/.rvm/gems/ruby-2.5.1/bin/halunke:23:in `<main>'
        12: from /home/me/.rvm/gems/ruby-2.5.1/bin/halunke:23:in `load'
        11: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/exe/halunke:22:in `<top (required)>'
        10: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/interpreter.rb:31:in `eval'
         9: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:4:in `eval'
         8: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:4:in `map'
         7: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:4:in `block in eval'
         6: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:77:in `eval'
         5: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:88:in `eval'
         4: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:88:in `each_slice'
         3: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:88:in `each'
         2: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:90:in `block in eval'
         1: from /home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:51:in `eval'
/home/me/.rvm/gems/ruby-2.5.1/gems/halunke-0.6.2/lib/halunke/nodes.rb:51:in `map': undefined method `node' for #<Halunke::ArrayNode:0x000055b23a3af740> (NoMethodError)
Did you mean?  nodes
```

However, this works:

```
('foo = {
    |'arr|
    (['a] = arr)
    (stdio puts a)
})

(foo call [["bar"]]) /* prints "bar" */
```

It'd be nice if we could destructure the arguments straight away.

_hope no syntax errors this time_

**Comment by moonglum** [comment]
Yep, that's true 👍 This feature is planned, I even had a half-working version of this once. This will be implemented.

**Comment by moonglum** [comment]
To say a few words more about this: Halunke solves destructuring differently than other languages (I don't know any other language that solved it like this). Destructuring is just the method `=` 😸 This works, because you can send messages to uninitialized variables (in fact, that's the only way to assign them a value). So there is no syntax for destructuring in Halunke, it's just a message. This works pretty nicely from what I've found so far, but made this particular part a little tricky, leading to a knot in my brain. I therefore decided to delete the code I wrote back then and get back to it with a fresh cup of coffee ☕️

**Comment by sarna** [comment]
Awesome :eyes: 

But then
```
('foo = {
    |['a]|
    (stdio puts a)
})

(foo call [["bar"]])
```
should just call `(['a] = ["bar"])` somewhere behind the scenes, no?

**Comment by moonglum** [comment]
Yes, exactly 👍 The problem is: `(['a] = ["bar"])` itself is a message send. In the message send. And this, again, would do the pattern matching. Which is another message send. And this... will never stop. So I guess there needs to be a trick somewhere 🤔

**Comment by sarna** [comment]
Would it be possible to support things like these? (Elixir) :thinking: 
```elixir
defmodule Foo do
    def f([a, b, c]) do
        IO.puts(c)
    end
    def f([a, b]) do
        IO.puts(b)
    end
    def f([a]) do
        IO.puts(a)
    end
end

Foo.f([1, 2, 3]) # prints 3
Foo.f([1, 2]) # prints 2
Foo.f([1]) # prints 1
```
You can't assign to something twice in Halunke, so I doubt it. But it would be soo convenient.

**Comment by sarna** [comment]
Oh, sweet!
